---
title: "Materiales"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

Acá puede encontrar los materiales del curso. Las clases, presentaciones, tareas y otros se basan en distintas fuentes. Incluyo referencias que pueden ser útiles para entender mejor los conceptos.

<br>

# Programa (Syllabus)

La versión más reciente del programa del curso [acá.](materials/MacroLabor.pdf)

<br>

# Tesis 1

<br>

### Modelo Neoclásico del mercado laboral

* Capítulos 1 y 2 de Cahuc, Carcillo y Zylberberg
* [Notas](materials/Modelo_neoclasico.pdf)
* [Tarea 1](materials/Tarea_1.pdf)

# Tesis 2 

<br>

### Búsqueda unilateral

* Capítulo 5 Ljundqvist y Sargent 
* Capítulo 17 del [GLS](https://www3.nd.edu/~esims1/GLS_may_2021.pdf) 
* Notas modelo [McCall](materials/McCall.pdf)
* [Tarea 2](materials/Tarea_2.pdf)


# Tesis 3 

<br>

### Búsqueda bilateral

* Capítulo 1 de Pissarides. Capítulo 9 de Cahuc, Carcillo y Zylberberg
* Notas modelo [DMP](materials/Modelo_DMP.pdf)
* [Tarea 3](materials/Tarea_3.pdf)

# Tesis 4 

<br>

### Modelo de búsqueda y reclutamiento

* [Notas del modelo](materials/recruiting_model.pdf)
* [Notas determinación salarial](materials/Determinacion_salarial.pdf)
* [Notas fluctuaciones del desempleo](materials/fluctuacion_u.pdf)

### Fluctuaciones del desempleo

* Notas
