---
title: "Referencias"
output: html_document
---
<br>

### Referencias bibliográficas

* [*Labor Economics*](https://mitpress.mit.edu/books/labor-economics-second-edition) de  Pierre Cahuc, Stéphane Carcillo y André Zylberberg.
* [*Equilibrium Unemployment Theory*](https://mitpress.mit.edu/books/equilibrium-unemployment-theory-second-edition#:~:text=An%20equilibrium%20theory%20of%20unemployment,the%20private%20gains%20from%20trade.) de Christopher Pissarides.
* [*Wage Dispersion: Why Are Similar Workers Paid Differently?*](https://mitpress.mit.edu/books/wage-dispersion) de Dale T. Mortensen.
* [*Recursive Macroeconomic Theory*](https://mitpress.mit.edu/books/recursive-macroeconomic-theory-fourth-edition) de Lars Ljungqvist y Thomas J. Sargent
* [*Intermediate Macroeconomics*](https://www3.nd.edu/~esims1/GLS_may_2021.pdf) de Julio Garín, Robert Lester y Eric Sims 

<br>

### Datos

* Indicadores económicos del [BCCR](https://www.bccr.fi.cr/indicadores-economicos)
*
<br>


### Códigos

* Implementación del modelo de McCall por [QuantEcon](https://python.quantecon.org/mccall_model.html)

### Publicaciones y artículos

<br>

#### Oferta y participación laboral

* Faberman, R. J., Mueller, A. I., & Şahin, A. (2022). Has the Willingness to Work Fallen during the Covid Pandemic? (No. w29784). National Bureau of Economic Research.[Link](https://www.nber.org/system/files/working_papers/w29784/w29784.pdf)

* Aguiar, M., Bils, M., Charles, K. K., & Hurst, E. (2021). Leisure luxuries and the labor supply of young men. Journal of Political Economy, 129(2), 337-382. [Link](https://www.markaguiar.com/files/leisure_luxuries.pdf)

* The great resignation: [Wikipedia](https://en.wikipedia.org/wiki/Great_Resignation), [NPR](https://www.npr.org/sections/money/2022/01/25/1075115539/the-great-resignation-more-like-the-great-renegotiation)

<br>

#### Determinación salarial

* Hall, R. E., & Krueger, A. B. (2012). Evidence on the incidence of wage posting, wage bargaining, and on-the-job search. American Economic Journal: Macroeconomics, 4(4), 56-67. [Link](https://www.nber.org/system/files/working_papers/w29874/w29874.pdf) [Descarga](materials/HallKrueger2012AEJ.pdf)
* Acemoglu, D., He, A. X., & le Maire, D. (2022). Eclipse of Rent-Sharing: The Effects of Managers’ Business Education on Wages and the Labor Share in the US and Denmark.  4059303.[Link](https://www.nber.org/system/files/working_papers/w29874/w29874.pdf)